version: "3.9"

services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: quotes-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ".mysql-data:/var/lib/mysql"

  redis:
    image: redis:6.2-alpine
    container_name: quotes-redis
    ports:
      - "6379:6379"
